### ISSUE TITLE
404 not loading

### ISSUE THREAD

**Issue by fobHub** [justintadlock/stargazer#22]
There seems to be a bug loading the "/content/error.php" file. (My configuration is a configuration with homepage (page) in front and blog on a specific blog page. The problem occurs on two servers.)

If I produce an error (loading the page /ölkajsdf/ for example) - it rewinds all the posts instead of showing the error template..Look and feel is like the blog page, only the breadcrumb recognizes that we have an error. 

I now made a copy from "/content/content.php" (where I had to make some changes anyway) and wrapped it into an "if ( !is_404() )" request so that it loads the error.php from there (after including another get_template_part request.)

But I think I will now grab a copy of the index.php to wrap the post checking part into the same conditional request and prevent it from loading posts for error pages, too. I do not know why it does not recognize that there are no posts to be shown.

**Comment by justintadlock** [comment]
Everything is working for me with this.  The `content/error.php` template is loaded.  You can always add a `404.php` template too.  Leaving this open until further feedback.

**Comment by justintadlock** [comment]
Closing since no feedback was given.
