### ISSUE TITLE
Dropdown menus don't appear on tablet

### ISSUE THREAD

**Issue by sdayman** [justintadlock/stargazer#38]
On Twenty Thirteen theme (http://twentythirteendemo.wordpress.com/), tapping on "Blog Archives" makes the dropdown menu appear. A second tap follows link for menu title or submenu entries.

On Stargazer theme (http://locallylost.com/stargazer/), tapping on "About" follows link to About page. For a dropdown menu, such as "Post Formats," with a Custom URL Title using a blank or # URL, the dropdown menu does not appear.

This looks like it's handled by CSS, as the HTML for both examples looks the same.

**Comment by justintadlock** [comment]
The mobile menu now appears at screen sizes 1024px and below: https://github.com/justintadlock/stargazer/commit/48c25b8744afb102bfa612f2c29ab75342638156
