### ISSUE TITLE
1.2.1 - Buggy behavior when navigating to next/previous set of pages using the navigation links

### ISSUE THREAD

**Issue by MartyMacGyver** [justintadlock/stargazer#41]
Given a blog with many pages, the navigation at the bottom is not working correctly.
(e.g., ← Previous 1 2 3 Next →)

One expects the following form of link for, say, the "2" or "Next" links in the above example when still on the first page of pages (which is consistent with other navigation on the site for posts and such):
http://www.example.com/index.php/page/2

Instead, the following link is generated, leading to a 404 error when navigated to:
http://www.example.com/page/2

It appears only the pager has this problem - navigating from post to post via the Previous/next links at the bottom of a given single post seems to work fine. This works correctly with other themes I tested this against.

**Comment by justintadlock** [comment]
Closing this because we're moving to the newer core WP `the_posts_pagination()`.
