### ISSUE TITLE
Mobile menu: Label 'Secondary Menu' appears next to menu icon

### ISSUE THREAD

**Issue by queridamolly** [justintadlock/stargazer#44]
When I view this theme on my iPhone 4s, a 'Secondary Menu' label appears next to the menu (or hamburger) icon. This label obscures the site title-- please remove!

I believe the same thing is true whether the menu is primary or secondary.

Over than the issues with mobile menus, I LOVE this theme. Thank you for making it available for free!

![5957ca0c-5913-4520-b948-6d357112ee51](https://cloud.githubusercontent.com/assets/8763857/4262403/45c1ca80-3ba0-11e4-991f-010f11543a96.png)

**Comment by cybermarmotte** [comment]
You can delete it in the php but when updating the theme, you lost your modifications, maybe it can be a tick box to select wether you want it appears or not. Let's see what the dev will say about that.

**Comment by justintadlock** [comment]
That last commit should finally fix this issue.
