### ISSUE TITLE
Images show up twice on main page

### ISSUE THREAD

**Issue by scotthraban** [justintadlock/stargazer#48]
Any time I add an image to a post, it ends up showing up above the title of the post, as well as in the body of the post.

It seems like it is treating the image as a features image, although the post does not have a featured image associated with it.

Note that this is only on the main page - on the page for the individual post, the image only shows up in the body of the post.

This appears to be quite a common issue:
https://wordpress.org/support/topic/duplicate-picture-displays-above-post-heading?replies=4
https://wordpress.org/support/topic/image-before-post?replies=2
https://wordpress.org/support/topic/featured-images-55?replies=2
https://wordpress.org/support/topic/how-to-remove-wide-images-above-post-tile-in-homepage?replies=4

**Comment by scotthraban** [comment]
I mucked about, and if I change the params to get_the_image in content.php to be just "featured" instead of "featured" and "attachment", then the extra image goes away. Or of course if I just remove the call to get_the_image altogether.

Not quite sure how to make this stick with a target child theme change, guess I will override the whole template.

**Comment by justintadlock** [comment]
Can you link to a post where you're getting a double image?  Stargazer should only call for the image on single posts if it's an "image" post (post format).  Even then though, it should be stripping the image from the post content.

**Comment by justintadlock** [comment]
Based on the topics you linked to and a closer reading, this looks to be expected behavior. I'm going to this one as "wontfix".
