### ISSUE TITLE
loop_pagination error with HC 3.0+

### ISSUE THREAD

**Issue by redactuk** [justintadlock/stargazer#50]
Stargazer v1.2.1 and on clean Wordpress 4.2.2 install updated to HC3.0 dev, error reported:

`Fatal error: Call to undefined function loop_pagination() in C:\wamp\client2\wp-content\themes\stargazer\misc\loop-nav.php on line 10`

**Comment by justintadlock** [comment]
You shouldn't be updating the Hybrid Core in Stargazer.  That's my job.  All you have to worry about is updating the Stargazer theme whenever it gets an update.
