### ISSUE TITLE
embed-wrap causes the WP 4.4 oEmbeds to not resize correctly

### ISSUE THREAD

**Issue by pento** [justintadlock/stargazer#52]
The oEmbed iframes resize themselves to fit their content, but there's a CSS rule that seems to be overriding it. 

**To Reproduce**

* Install Stargazer on WP nightly
* Create a new post with a WP embed (for example, paste https://make.wordpress.org/core/2015/10/28/new-embeds-feature-in-wordpress-4-4/ on a new line in the editor)
* Publish, then view post

**Result**

The correct height is being set on the iframe, but it's being overridden by Stargazer's CSS.

**Comment by swissspidy** [comment]
Jetpack solves this by only applying that iframe fix to actual video embeds, see https://github.com/Automattic/jetpack/pull/2440

**Comment by justintadlock** [comment]
That should be corrected in the 1.3 branch.  We can reopen if need be.
