### ISSUE TITLE
[Request Feature] Site Logo

### ISSUE THREAD

**Issue by first087** [justintadlock/stargazer#55]
Please enable Site Logo for Jetpack

Ref. https://jetpack.me/support/site-logo/

**Comment by justintadlock** [comment]
I don't support Jetpack, but I'm open to the idea of adding a logo option to the theme.

**Comment by first087** [comment]
I think, Jetpack Site Logo is easy to use.

**Comment by justintadlock** [comment]
Like I said, I'm open to adding a logo option within the theme itself.  However, I do not plan to add support for Jetpack.

**Comment by justintadlock** [comment]
Now that core WP is getting the site logo feature, I'd like to revisit this idea.

**Comment by justintadlock** [comment]
Closing this now.  Support for core's site logo was added in https://github.com/justintadlock/stargazer/commit/f1ae66eab1d05096a36906766f116f05ef5c3dc3
