### ISSUE TITLE
Different behaviour and functionnalities between stargazer and child theme

### ISSUE THREAD

**Issue by cybermarmotte** [justintadlock/stargazer#57]
Hye,

As you can see on those two screenshots, you can see the different behavioor between the main stargazer theme and the child one. Can you add the same behaviour as such as behing able to easily edit the footer. I add a +1 to manage logo. ANyway, thanks for your job your theme's rock!

![stargazer](https://cloud.githubusercontent.com/assets/3687099/13466803/de9b3e2a-e09b-11e5-9ca4-1e56a216b73c.png)
![exastris](https://cloud.githubusercontent.com/assets/3687099/13466804/de9d93c8-e09b-11e5-9971-dec56656fd4c.png)

**Comment by justintadlock** [comment]
I don't understand.  Can you describe what's going on in more detail?

**Comment by cybermarmotte** [comment]
I mean, on child theme I'm able to easily customize the css, on main stargazer I'm not. Is it a little bit clearer?

**Comment by m-e-h** [comment]
@cybermarmotte are you talking about the jetpack edit CSS module? I haven't tried it but there's no reason that it wouldn't work on stargazer. Maybe check to make sure the module is active in that plugin.

**Comment by cybermarmotte** [comment]
No no, I'm not talking about the Jetpack module, see my two screenshots, this two different wordpress websites, one with the main stargazer and the other one with stargazer and the ex astris child theme. When ex astris is activated, you get the edit css feature not on the stargazer only.

**Comment by cybermarmotte** [comment]
I tried just right now to install jetpack on the other website and it didn't change anything.

**Comment by m-e-h** [comment]
Your bottom screenshot is a plugin, I promise. The other difference between the screenshots is that "Jetpack" is listed as active in the sidebar on the second one.

**Comment by cybermarmotte** [comment]
![capture](https://cloud.githubusercontent.com/assets/3687099/13601090/c4dde154-e52d-11e5-98d9-e5fdf224cf99.PNG)

**Comment by justintadlock** [comment]
Yeah, the edit CSS menu doesn't have anything to do with the theme.  That's some plugin (looks like Jetpack's CSS module).
