### ISSUE TITLE
Do we need to add class for Custom Logo?

### ISSUE THREAD

**Issue by ernilambar** [justintadlock/stargazer#58]
May we need not add this as WP core already adds this class in `body` when Custom Logo is active. 

`
if ( function_exists( 'has_custom_logo' ) && has_custom_logo() )
    $classes[] = 'wp-custom-logo';
`

**Comment by justintadlock** [comment]
Hybrid Core already adds this: https://github.com/justintadlock/hybrid-core/commit/d8ff89385df63a0eb5b0eb05a4c3e09cc52a773e

**Comment by ernilambar** [comment]
What I meant is that we may not have to add that class as WP itself add it.

**Comment by justintadlock** [comment]
Hybrid Core completely overwrites all the `<body>` classes.  So, WP can't add it.  HC has to add it.

**Comment by ernilambar** [comment]
Hmm I was not aware abt that.
