### ISSUE TITLE
Custom logo selective refresh issue in Customizer

### ISSUE THREAD

**Issue by ernilambar** [justintadlock/stargazer#59]
Whole page is refreshed when logo is uploaded first time. But after once there is logo, partial refresh works as expected when changed/removed. Not a critical issue but nice to be fixed. :)

Steps:
1. Fresh install
2. In Customizer -> Site Identity -> Logo, when you upload logo, whole page is refreshed. Custom Logo full supports Partial refresh in Customizer.

**Comment by m-e-h** [comment]
I saw this behavior with widgets as well. Wasn't sure if it was theme specific since I wasn't that familiar with selective refresh. Works fine after initial widget is selected.

**Comment by ernilambar** [comment]
@m-e-h I talked with Weston Ruter about widget in Customizer. And he told me that such behavior in wigdet's case is expected behavior. https://wordpress.slack.com/archives/core-customize/p1462255790000513

**Comment by m-e-h** [comment]
That makes sense. I would imagine the logo behaves the same way, for the same reasons as widgets. Right?

**Comment by ernilambar** [comment]
Its little bit different. Try Twenty Sixteen theme.
To fix this problem, what I found is that, `the_custom_logo()` should be called in either true or false condition of `has_custom_logo()`. In Customizer, `the_custom_logo()` generates some HTML markup (but hidden with CSS) which will enable partial refresh. If we call `the_custom_logo()` only when `has_custom_logo()` is true then, at first there will be no markup which aid for partial refresh.

**Comment by justintadlock** [comment]
I've been reviewing the core code.  We don't really need the `has_custom_logo()` check in `header.php` before outputting `the_custom_logo()`.

However, this part needs to stay:

	<?php if ( display_header_text() || has_custom_logo() ) : // If user chooses to display header text. ?>

Otherwise, the `<div id="branding">` gets output when it shouldn't.  I might be able to do something like this:

	<?php if ( display_header_text() || has_custom_logo() || is_customize_preview() ) : ?>

I'd want to make sure that's not breaking any designs though.
