### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by duckwatching** [justintadlock/stargazer#60]
There is a little problem in the german translation:
`#: misc/loop-nav.php:4
msgid "Previous Post: %link"
msgstr "﻿Previous Post: % link"`
The whitespace between "%" and "link" is a problem.
The translation is also a little bit outdated, so I made a new one. How can I commit this? Github or wordpress.org/Translations?
There are some pending issues with the german translation on wordpress.org so I am not sure about the right place.

**Comment by justintadlock** [comment]
Translations are now handled on WordPress.org.
