### ISSUE TITLE
Ability to display categories in Breadcrumbs

### ISSUE THREAD

**Issue by slaFFik** [justintadlock/stargazer#61]
This would be really nice to display category(ies) that were selected from a given post on a single post.

**Comment by justintadlock** [comment]
This is already possible.  Stargazer uses the Breadcrumb Trail library.  See: https://github.com/justintadlock/breadcrumb-trail#parameters

**Comment by slaFFik** [comment]
I meant something like a Customizer support, but ok.
Is it `$post_taxonomy` property?
