### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by paaljoachim** [justintadlock/stargazer#62]
Hey Justin

I downloaded the Stargazer theme and on activation received the following error message:

( ! ) Warning: require_once(/Users/joachim/Documents/Websites/test2-aug2017.dev/wp-content/themes/stargazer-master/library/hybrid.php): failed to open stream: No such file or directory in /Users/joachim/Documents/Websites/test2-aug2017.dev/wp-content/themes/stargazer-master/functions.php on line 28
--

1 | 0.0019 | 376864 | {main}( ) | ../customize.php:0
2 | 0.0023 | 436856 | require_once( '/Users/joachim/Documents/Websites/test2-aug2017.dev/wp-admin/admin.php' ) | ../customize.php:13
3 | 0.0025 | 454168 | require_once( '/Users/joachim/Documents/Websites/test2-aug2017.dev/wp-load.php' ) | ../admin.php:31
4 | 0.0026 | 463840 | require_once( '/Users/joachim/Documents/Websites/test2-aug2017.dev/wp-config.php' ) | ../wp-load.php:37
5 | 0.0031 | 588552 | require_once( '/Users/joachim/Documents/Websites/test2-aug2017.dev/wp-settings.php' ) | ../wp-config.php:90
6 | 0.2448 | 29316952 | include( '/Users/joachim/Documents/Websites/test2-aug2017.dev/wp-content/themes/stargazer-master/functions.php' ) | ../wp-settings.php:424

**Comment by justintadlock** [comment]
You need to do a recursive clone of the repository via Git.  The GitHub service doesn't package sub-modules into their ZIPs.

Or, you prefer a ZIP, grab the latest production copy from: http://wordpress.org/themes/stargazer

**Comment by paaljoachim** [comment]
Alrighty. Thanks Justin.
